### ISSUE TITLE
error

### ISSUE THREAD

**Issue by krampfstadtstudio** [7x11x13/bandcamp-auto-uploader#1]
i get this error when i want to open the app

﻿

Traceback (most recent call last):
File "__main__.py", line 27, in <module>
ImportError: attempted relative import with no known parent package
[8728] Failed to execute script '_main_' due to unhandled exception!

what should i do? I have installed Python 3.12 on Windows 10 64bit. I don't know anything about coding, this is all strange to me. How can I open the .exe file and make it work?

**Comment by 7x11x13** [comment]
Sorry about that, should be fixed in v0.2.7: https://github.com/7x11x13/bandcamp-auto-uploader/releases/tag/v0.2.7

**Comment by krampfstadtstudio** [comment]
thanks, it works now.
this is a game changer for me, I create sound effect libraries (https://krampfstadtstudio.bandcamp.com/) and until now I manually uploaded 25000+ sounds to BandCamp... so much time wasted... for example, one car library has 200-300 sounds, I needed more than 2 hours for that until now. THANKS A LOT FOR CREATING THIS!
________________________________________________________________________Danilo Crnogorac
www.imdb.com/name/nm5592832/www.linkedin.com/in/danilocrnogoracwww.soundkrampf.blogspot.com
 

    On Sunday, July 14, 2024 at 05:39:05 PM GMT+2, 7x11x13 ***@***.***> wrote:  
 
 


Sorry about that, should be fixed in v0.2.7: https://github.com/7x11x13/bandcamp-auto-uploader/releases/tag/v0.2.7
