### ISSUE TITLE
extension

### ISSUE THREAD

**Issue by krampfstadtstudio** [7x11x13/bandcamp-auto-uploader#2]
When I batch upload files, and today I wanted to upload 214 of them, they all have extension at the end of the name. Can this be removed?

for example, i uploaded file 'driving fast engine perspective', but it is named 'driving fast engine perspective.flac'

now i have to manualy rename all files to remove that '.flac'

**Comment by 7x11x13** [comment]
The program loads the metadata for each file and sets values based on that metadata. For the title, if no title metadata is found, it falls back to the file name. I would recommend some batch audio metadata editing program like mp3tag so you can set the title metadata for each file to be the file name (sans extension).

**Comment by krampfstadtstudio** [comment]
ok, and another thing, the files uploaded in order do not appear in that order on bandcamp. how to fix that? i want A to Z
________________________________________________________________________Danilo Crnogorac
www.imdb.com/name/nm5592832/www.linkedin.com/in/danilocrnogoracwww.soundkrampf.blogspot.com
 

    On Monday, July 15, 2024 at 03:40:35 PM GMT+2, 7x11x13 ***@***.***> wrote:  
 
 


The program loads the metadata for each file and sets values based on that metadata. For the title, if no title metadata is found, it falls back to the file name. I would recommend some batch audio metadata editing program like mp3tag so you can set the title metadata for each file to be the file name (sans extension).

**Comment by 7x11x13** [comment]
The files are sorted by track number, so you should use a program like mp3tag to set the tracknumber metadata in the order you want

**Comment by krampfstadtstudio** [comment]
thanks. i will try now to upload again
________________________________________________________________________Danilo Crnogorac
www.imdb.com/name/nm5592832/www.linkedin.com/in/danilocrnogoracwww.soundkrampf.blogspot.com
 

    On Monday, July 15, 2024 at 04:01:45 PM GMT+2, 7x11x13 ***@***.***> wrote:  
 
 


The files are sorted by track number, so you should use a program like mp3tag to set the tracknumber metadata in the order you want

**Comment by krampfstadtstudio** [comment]
still not good.
look at files order in mp3tag, you can see track numbers are A to Z

but files uploaded on bandcamp have this order



________________________________________________________________________Danilo Crnogorac
www.imdb.com/name/nm5592832/www.linkedin.com/in/danilocrnogoracwww.soundkrampf.blogspot.com
 

    On Monday, July 15, 2024 at 04:22:15 PM GMT+2, Danilo Crnogorac ***@***.***> wrote:  
 
 thanks. i will try now to upload again
________________________________________________________________________Danilo Crnogorac
www.imdb.com/name/nm5592832/www.linkedin.com/in/danilocrnogoracwww.soundkrampf.blogspot.com
 

    On Monday, July 15, 2024 at 04:01:45 PM GMT+2, 7x11x13 ***@***.***> wrote:  
 
 


The files are sorted by track number, so you should use a program like mp3tag to set the tracknumber metadata in the order you want

**Comment by 7x11x13** [comment]
Can you send me the tagged files so I can check what's happening? Any filesharing site will do

**Comment by krampfstadtstudio** [comment]
I'm sending the first 10 of 214 files https://we.tl/t-DUcgubgtZI
________________________________________________________________________Danilo Crnogorac
www.imdb.com/name/nm5592832/www.linkedin.com/in/danilocrnogoracwww.soundkrampf.blogspot.com
 

    On Monday, July 15, 2024 at 04:38:16 PM GMT+2, 7x11x13 ***@***.***> wrote:  
 
 


Can you send me the tagged files so I can check what's happening? Any filesharing site will do

**Comment by 7x11x13** [comment]
I see the problem, the tracknumbers are being sorted as if they were strings and not numbers, so it put "1" first then "10" before going to "2". Should be fixed in [v0.2.8](https://github.com/7x11x13/bandcamp-auto-uploader/releases/tag/v0.2.8), thank you for reporting

**Comment by krampfstadtstudio** [comment]
Nice, lets try again...


_______________________________________________________________________

Danilo Crnogorac


www.imdb.com/name/nm5592832/

www.linkedin.com/in/danilocrnogorac

www.soundkrampf.blogspot.com 
 
  On Mon, Jul 15, 2024 at 5:14 PM, ***@***.***> wrote:   


I see the problem, the tracknumbers are being sorted as if they were strings and not numbers, so it put "1" first then "10" before going to "2". Should be fixed in v0.2.8, thank you for reporting

**Comment by krampfstadtstudio** [comment]
it failed at track 44



________________________________________________________________________Danilo Crnogorac
www.imdb.com/name/nm5592832/www.linkedin.com/in/danilocrnogoracwww.soundkrampf.blogspot.com
 

    On Monday, July 15, 2024 at 05:18:41 PM GMT+2, Danilo Crnogorac ***@***.***> wrote:  
 
 Nice, lets try again...


_______________________________________________________________________

Danilo Crnogorac


www.imdb.com/name/nm5592832/

www.linkedin.com/in/danilocrnogorac

www.soundkrampf.blogspot.com 
 
  On Mon, Jul 15, 2024 at 5:14 PM, ***@***.***> wrote:   


I see the problem, the tracknumbers are being sorted as if they were strings and not numbers, so it put "1" first then "10" before going to "2". Should be fixed in v0.2.8, thank you for reporting
